version: "3.9"

services:
  apache:
    image: httpd:latest
    ports:
      - 8081:80
    volumes:
      - ./apache/html:/usr/local/apache2/htdocs/
      # - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - app-network

  python_api:
    build:
      context: ./python_api
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
      - prometheus
    networks:
      - app-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile 
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
      - exporters-network
      - app-network

    depends_on:
      - postgres_exporter
    links:
      - postgres_exporter

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://myuser:mypassword@db:5432/mydb?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - app-network
      - exporters-network
    depends_on:
      - db
  
  node_exporter:
    image: prom/node-exporter
    restart: always
    networks:
      - exporters-network
    ports:
      - 9100:9100

  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      networks:
        - monitoring-network 
      depends_on:
        - postgres_exporter
        - db
        - node_exporter
        - python_api
        - prometheus
      volumes:
        - ./grafana/defaults.ini:/etc/grafana/conf/defaults.ini:ro
        - ./grafana/provisioning:/etc/grafana/provisioning
        - grafana_data:/var/lib/grafana
        - grafana_log:/var/log/grafana
    
  blackbox:
    image: prom/blackbox-exporter:latest
    privileged: true
    volumes:
      - ./prometheus/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'
    networks:
      - app-network
      - exporters-network
    depends_on: 
      - db
      - python_api
      - prometheus
      - apache

networks:
  app-network:
  exporters-network:
  monitoring-network:

volumes:
  grafana_data:
  grafana_log: