version: "3.9"

services:
  python_api:
    build:
      context: ./python_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - prometheus
    networks:
      - my-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile 
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    networks:
      - my-network
    depends_on:
      - postgres_exporter
    links:
      - postgres_exporter

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - my-network

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://myuser:mypassword@db:5432/mydb?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - my-network
    depends_on:
      - db

networks:
  my-network:

