apiVersion: 1
providers:
  alerts:
    name: "alerts"
    type: "file"
    folder: ""
    folderUid: ""
    options:
      path: "/etc/grafana/provisioning/alerts"
      foldersFromFilesStructure: true
      disableDeletion: true
      updateIntervalSeconds: 10
      allowUiUpdates: true
  dashboards:
    name: "dashboards"
    type: "file"
    folder: ""
    folderUid: ""
    options:
      path: "/etc/grafana/provisioning/dashboards"
      foldersFromFilesStructure: true
      disableDeletion: true
      updateIntervalSeconds: 10
      allowUiUpdates: true
