global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'python_api'
    static_configs:
      - targets: ['python_api:8888']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  
  - job_name: 'blackbox'
    metrics_path: /metrics
    static_configs:
      - targets:
        - blackbox:9115
  
  - job_name: 'blackbox-http'
    # scheme: http
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://apache:80        # fake local web service.
        - http://apache:80/page2.html
        - http://python_api:8888/slow-endpoint
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.