apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
    - name: Prometheus Data Source
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      id: my-prometheus-datasource
      isDefault: true
      version: 1
      editable: true
      basicAuth: false
      jsonData:
        graphiteVersion: "1.1"
        tlsAuth: false
        tlsAuthWithCACert: false
      secureJsonData:
        tlsCACert: "..."
        tlsClientCert: "..."
        tlsClientKey: "..."
